In [1]:
pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 28.0 MB/s eta 0:00:00a 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5])
print(my_array)
# ndarray stands for n dimension array
print(type(my_array))
#  Blank in the second entry means there is nothing there
# i.e. this is just a single row and not a table
print(my_array.shape)

my_second_array = np.array([1, 2, 3, 4, 5])
my_second_array.reshape(1, 5)  # 1 row and 5 columns

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


array([[1, 2, 3, 4, 5]])

In [7]:
my_range_array = np.arange(0, 10, 2).reshape(5, 1)
print(my_range_array)

[[0]
 [2]
 [4]
 [6]
 [8]]


In [14]:
ones = np.ones((3, 4))
print(ones)
print()
zeroes = np.zeros((3, 4))
print(zeroes)
print()
identity = np.eye(3, 3)
print(identity)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
